[package]
name = "go-pro-metadata"
version = "0.1.0"
authors = ["Jamie Bowers <james.t.k.bowers@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.1.0"